# Assessment DISC - Configuração Render.com
# Deploy automático para aplicação Streamlit

services:
  - type: web
    name: assessment-disc-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run nexus_assistant.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false 